# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
future: false
paginate: 5
excerpt_separator: ""

author: Mitchell Hanberg
