# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
excerpt_separator: ""

author: Mitchell Hanberg
