# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-algolia
include:
  - _redirects
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
future: false
excerpt_separator: ""

author: Mitchell Hanberg
url: https://www.mitchellhanberg.com
title: Mitchell Hanberg
twitter:
  username: mitchhanberg
  card: summary
logo: https://res.cloudinary.com/mhanberg/image/upload/v1574047220/Becca___Mitch-67_copy.jpg
