# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock
  - node_modules
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
future: false
excerpt_separator: ""

author: Mitchell Hanberg
url: https://www.mitchellhanberg.com
title: Mitchell Hanberg
twitter:
  username: mitchhanberg
  card: summary
logo: images/256_m_black_white_background.png
