[build]
  command = "bin/gen && bundle exec jekyll algolia"
  publish = "_site"
  functions = "functions/"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"

[[plugins]]
  package = "netlify-plugin-no-more-404"

  [plugins.inputs]
    on404 = "warning" 
