[build]
  command = "mix local.hex --force && mix local.rebar --force && mix deps.get && MIX_ENV=prod mix tableau.build"
  publish = "_site"
  functions = "functions/"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"

[[plugins]]
  package = "netlify-plugin-no-more-404"

  [plugins.inputs]
    on404 = "warning" 
