name: Netlify Deploy

on:
  schedule:
  # 6am ET, posts will publish if rebuilt after 1am ET
  - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: ${{ secrets.NETLIFY_DEPLOY_CMD }}

