name: Netlify Deploy

on:
  push:
  workflow_dispatch:
  schedule:
    # 6am ET, posts will publish if rebuilt after 1am ET
    - cron: "0 10 * * *"

jobs:
  build:
    env:
      HARDCOVER_TOKEN: ${{ secrets.HARDCOVER_TOKEN }}
      GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
      MIX_ENV: prod
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
        with:
          extra_conf: |
            extra-substituters = https://mhanberg.cachix.org
            extra-trusted-public-keys = mhanberg.cachix.org-1:tpHVw70kbGnO5mGv4rA3pjxpqeEiP/vWfJT4tVaK85o=
            accept-flake-config = true
      - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
        with:
          name: mhanberg
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          useDaemon: false
          cachixArgs: "--verbose"

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/flake.nix') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Remove stale goodreads data
        run: rm _build/books.bin

      - name: Install Dependencies
        run: nix develop .#netlify --command bash -c 'mix deps.get'

      - name: Build
        run: nix develop .#netlify --command bash -c 'mix build'

      - name: Deploy Branch Preview
        if: ${{ github.ref_name != 'main' }}
        run: nix develop .#netlify --command bash -c 'netlify deploy --alias ${{ github.ref_name}}'

      - name: Deploy Production
        if: ${{ github.ref_name == 'main' }}
        run: nix develop .#netlify --command bash -c 'netlify deploy --prod'
